const WAVESPEED_URL = "https://api.wavespeed.ai/api/v3/google/nano-banana-pro";

class WavespeedHttpError extends Error {
  constructor(message, statusCode, payload) {
    super(message);
    this.name = "WavespeedHttpError";
    this.statusCode = statusCode;
    this.payload = payload;
  }
}

function isProductUnavailableError(error) {
  const message = String(error?.message || "").toLowerCase();
  return message.includes("product not found") || message.includes("not found");
}

function extractText(payload) {
  if (!payload || typeof payload !== "object") {
    return "";
  }

  if (typeof payload.text === "string") return payload.text;
  if (typeof payload.output === "string") return payload.output;
  if (typeof payload.result === "string") return payload.result;
  if (typeof payload.message === "string") return payload.message;

  const choices = Array.isArray(payload.choices) ? payload.choices : [];
  const firstChoice = choices[0];
  if (firstChoice?.message?.content) return String(firstChoice.message.content);
  if (typeof firstChoice?.text === "string") return firstChoice.text;

  if (Array.isArray(payload.data) && typeof payload.data[0] === "string") return payload.data[0];
  return "";
}

function tryParseJsonFromText(text) {
  if (!text || typeof text !== "string") return null;

  const direct = text.trim();
  try {
    return JSON.parse(direct);
  } catch (_error) {
    // Continue to bracket extraction fallback.
  }

  const jsonMatch = direct.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
  if (!jsonMatch) return null;

  try {
    return JSON.parse(jsonMatch[0]);
  } catch (_error) {
    return null;
  }
}

async function callWavespeed(prompt) {
  const apiKey = process.env.WAVESPEED_API_KEY;
  if (!apiKey) {
    throw new Error("WAVESPEED_API_KEY is missing in .env");
  }

  const response = await fetch(WAVESPEED_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ prompt })
  });

  let data = null;
  try {
    data = await response.json();
  } catch {
    data = null;
  }

  if (!response.ok) {
    const fallbackMessage =
      response.status === 401
        ? "Unauthorized: invalid Wavespeed API key."
        : response.status === 429
        ? "Rate limit exceeded by Wavespeed. Please retry shortly."
        : "Wavespeed request failed";

    throw new WavespeedHttpError(
      data?.error || data?.message || fallbackMessage,
      response.status,
      data
    );
  }

  const text = extractText(data);
  return { data, text };
}

function jsonInstruction(schemaDescription) {
  return `Return ONLY valid JSON. Do not include markdown. Schema: ${schemaDescription}`;
}

function sendAiError(res, error) {
  if (error instanceof WavespeedHttpError) {
    return res.status(error.statusCode).json({
      error: error.message,
      statusCode: error.statusCode,
      provider: "wavespeed"
    });
  }

  const message = error?.message || "API error";
  return res.status(500).json({ error: message, statusCode: 500 });
}

export const generateAI = async (req, res) => {
  const { prompt } = req.body || {};
  if (!prompt) {
    return res.status(400).json({ error: "prompt is required" });
  }

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    return res.json({ text, parsed, raw: data });
  } catch (error) {
    if (isProductUnavailableError(error)) {
      return res.json({
        text: "Wavespeed product unavailable. Using fallback AI response.",
        parsed: {
          note: "Fallback response generated by Virnova backend.",
          promptPreview: String(prompt).slice(0, 240)
        },
        fallback: true,
        warning: "Wavespeed product unavailable; using local fallback."
      });
    }
    return sendAiError(res, error);
  }
};

export const generateScript = async (req, res) => {
  const { niche, topic, audience } = req.body || {};
  if (!niche || !topic || !audience) {
    return res.status(400).json({ error: "niche, topic, and audience are required" });
  }

  const prompt = `Generate a viral Instagram Reel script.

Niche: ${niche}
Topic: ${topic}
Audience: ${audience}

Provide:
- Hook (very attention-grabbing)
- Script (short and engaging)
- Loop ending
- Caption
- Hashtags (10 trending)

Make it highly viral and engaging.
${jsonInstruction(
    '{"hook":"string","script":"string","loopEnding":"string","caption":"string","hashtags":["#tag1","#tag2"]}'
  )}`;

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    if (parsed) return res.json(parsed);

    return res.json({
      hook: "",
      script: text || "No script generated",
      loopEnding: "",
      caption: "",
      hashtags: [],
      raw: data
    });
  } catch (error) {
    if (isProductUnavailableError(error)) {
      return res.json({
        hook: `Stop scrolling! ${niche} creators are missing this ${topic} pattern.`,
        script: `Hook your ${audience} audience in 2 seconds, show one actionable ${topic} method, then close with a clear CTA to save and follow for part 2.`,
        loopEnding: "Want the advanced version? Comment 'PART 2' and follow for the next breakdown.",
        caption: `${topic} made simple for ${audience}. Save this before your next upload.`,
        hashtags: ["#viral", "#reels", "#contentcreator", `#${String(niche).replace(/\s+/g, "")}`, "#growth"],
        fallback: true,
        warning: "Wavespeed product unavailable; using local script fallback."
      });
    }
    return sendAiError(res, error);
  }
};

export const generateIdeas = async (req, res) => {
  const { niche } = req.body || {};
  if (!niche) return res.status(400).json({ error: "niche is required" });

  const prompt = `Generate 10 viral content ideas.

Niche: ${niche}

For each idea provide:
- Title
- Hook
- Short explanation

Make ideas trendy and engaging.
${jsonInstruction('[{"title":"string","hook":"string","explanation":"string"}]')}`;

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    if (Array.isArray(parsed)) return res.json({ ideas: parsed });
    if (Array.isArray(parsed?.ideas)) return res.json({ ideas: parsed.ideas });

    return res.json({ ideas: [], rawText: text, raw: data });
  } catch (error) {
    if (isProductUnavailableError(error)) {
      return res.json({
        ideas: [
          {
            title: `${niche} Myth vs Fact`,
            hook: `Most people get ${niche} wrong. Here is the truth in 20 seconds.`,
            explanation: "Quick myth-busting format with high save potential."
          },
          {
            title: `${niche} 3-Step Framework`,
            hook: `Use this 3-step ${niche} framework before your next post.`,
            explanation: "Educational short that drives comments and shares."
          },
          {
            title: `${niche} Beginner Mistakes`,
            hook: `Avoid these 3 beginner mistakes in ${niche}.`,
            explanation: "Pain-point format that improves retention."
          }
        ],
        fallback: true,
        warning: "Wavespeed product unavailable; using local ideas fallback."
      });
    }
    return sendAiError(res, error);
  }
};

export const generateCaptionHashtags = async (req, res) => {
  const { topic, niche } = req.body || {};
  if (!topic || !niche) return res.status(400).json({ error: "topic and niche are required" });

  const prompt = `Generate a viral caption and hashtags.

Topic: ${topic}
Niche: ${niche}

Provide:
- Caption (engaging + emotional)
- 15 hashtags (viral + niche based)
${jsonInstruction('{"caption":"string","hashtags":["#tag1","#tag2"]}')}`;

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    if (parsed) return res.json(parsed);
    return res.json({ caption: text || "", hashtags: [], raw: data });
  } catch (error) {
    if (isProductUnavailableError(error)) {
      return res.json({
        caption: `This ${topic} breakdown is for creators in ${niche} who want higher engagement. Save this and share with your team.`,
        hashtags: [
          "#viral",
          "#trending",
          `#${String(niche).replace(/\s+/g, "")}`,
          `#${String(topic).replace(/\s+/g, "")}`,
          "#contentstrategy"
        ],
        fallback: true,
        warning: "Wavespeed product unavailable; using local caption fallback."
      });
    }
    return sendAiError(res, error);
  }
};

export const analyzeTrends = async (req, res) => {
  const { niche } = req.body || {};
  if (!niche) return res.status(400).json({ error: "niche is required" });

  const prompt = `Analyze viral trends in this niche:

Niche: ${niche}

Provide:
- Top hooks used
- Common keywords
- Content style
- Emotional triggers
- Best posting tips
${jsonInstruction(
    '{"topHooks":["string"],"keywords":["string"],"contentStyle":"string","emotionalTriggers":["string"],"bestPostingTips":["string"]}'
  )}`;

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    if (parsed) return res.json(parsed);
    return res.json({ topHooks: [], keywords: [], contentStyle: "", emotionalTriggers: [], bestPostingTips: [], raw: data });
  } catch (error) {
    // Graceful fallback so dashboard tools keep working if a provider product is unavailable.
    if (isProductUnavailableError(error)) {
      const nicheLabel = String(niche || "content").trim();
      return res.json({
        topHooks: [
          `Stop scrolling: ${nicheLabel} creators are doing this wrong`,
          `I tested 3 ${nicheLabel} formats and only one went viral`,
          `This ${nicheLabel} trick boosted retention in 24 hours`
        ],
        keywords: ["viral", "retention", "hook", nicheLabel],
        contentStyle: "Fast-paced short-form with clear value and CTA",
        emotionalTriggers: ["Curiosity", "Urgency", "Relatability", "Inspiration"],
        bestPostingTips: [
          "Post during evening peak slots and test 2 hook variations",
          "Keep first 2 seconds punchy with text overlays",
          "End with a question to increase comments and saves"
        ],
        fallback: true,
        warning: "Wavespeed product unavailable; using local trend fallback."
      });
    }
    return sendAiError(res, error);
  }
};

export const generateHooks = async (req, res) => {
  const { topic, niche } = req.body || {};
  if (!topic || !niche) return res.status(400).json({ error: "topic and niche are required" });

  const prompt = `Generate 10 viral hooks.

Topic: ${topic}
Niche: ${niche}

Hooks must be:
- Short
- Scroll-stopping
- Curiosity-driven
${jsonInstruction('{"hooks":["string"]}')}`;

  try {
    const { data, text } = await callWavespeed(prompt);
    const parsed = tryParseJsonFromText(text);
    if (Array.isArray(parsed)) return res.json({ hooks: parsed });
    if (Array.isArray(parsed?.hooks)) return res.json({ hooks: parsed.hooks });
    return res.json({ hooks: [], rawText: text, raw: data });
  } catch (error) {
    if (isProductUnavailableError(error)) {
      return res.json({
        hooks: [
          `You are one ${topic} tweak away from better reach.`,
          `This ${niche} trick works even if you have low views.`,
          `Steal this ${topic} hook format before everyone uses it.`,
          `Most creators ignore this ${niche} growth signal.`,
          `Try this before your next ${topic} upload.`
        ],
        fallback: true,
        warning: "Wavespeed product unavailable; using local hooks fallback."
      });
    }
    return sendAiError(res, error);
  }
};
